import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from "next/link";

export default function Layout({children}) {
  return (
    <>
      <Head>
        <title>Hello World</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <ul>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/about">About</Link></li>
            <li><Link href="/time">Time</Link></li>
          </ul>

          {children}
      </main>
    </>
  )
}
